name: Photography by Sebastian
favicon: null
layout_spectrum: 0.9729547710157931
typography_spectrum: 0.8969452411402017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.09498564968816936
  lightness: 0.6497597300913185
  saturation: 0.9037647328805178
  rhythmicContrast: 0.6391180010978132
purpose: []
